### ISSUE TITLE
Children update is ignored when animation is in progress

### ISSUE THREAD

**Issue by mondaychen** [marnusw/react-css-transition-replace#38] opened 2017-02-17 22:31 UTC
You can easily reproduce this bug in the "Cross-fade transition" example in demo.

If you quickly click twice (like doubleclick) on the image, the page will show the 2nd image. But at this moment, the parent component has already changed its state twice (swapped: false->true->false) and expecting `<ReactCSSTransitionReplace>` to show the 1st image. Apparently `<ReactCSSTransitionReplace>` ignored the 2nd change because the animation was not completed.

Now if you click on the image again (swapped is changed to true), nothing will happen on the page.

**Comment by marnusw** [comment] 2017-02-28 07:41
I have merged #34 which might help with this issue, although it seems that didn't quite solve it. I've been working on pretty much a complete rewrite of the library on the `next` branch. I think that might solve what you're seeing. It's probably not quite ready for a release and I haven't had time to work on it in a while, but if you find it a step in the right direction feel free to create PRs against it. I'll put in some more time when I can.

If this is a duplicate of #29 let's continue the discussion there.

**Comment by mondaychen** [comment] 2017-02-28 16:06
#34 does help. Now it will correctly show the new child, but it will also discard animation of both entering and leaving process.

![feb-28-2017 10-53-14](https://cloud.githubusercontent.com/assets/1001890/23412785/b954fd82-fda4-11e6-8697-88a2a4b28010.gif)

And I checked out `next` branch -- it does look better. Looking at the source code, I think it's definitely the right direction.

![gif2](https://cloud.githubusercontent.com/assets/1001890/23413130/cb16c6a8-fda5-11e6-9dae-9c79d1af5e45.gif)

Anything I can do to help the rewrite? Do you have a list of TODOs?

**Comment by marnusw** [comment] 2017-03-08 22:18
Thanks for the offer to help @mondaychen. I have opened #42 which gives a simple to-do list and this version can also be installed from npm as `3.0.0-beta.1` if you are comfortable with it.

**Comment by marnusw** [comment] 2017-08-27 21:38
Version 3 has been released. Further issues can be opened if this version does not solve all of the above.

**Closed by marnusw** 2017-08-27 21:38 UTC
